#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

OPTIONS="--add name --hostname name --polar disabled --text-minimum 8 --text-maximum 1024 --text jws-secret --required --url-path-abempty path --relation-base /etc/device/services/db/postgresql/database --relation-name name --relation-suffix .txt --relation database"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart tomcat-autodiscovery@${device.tomcat.instance}.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi


