#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --mark name --hostname name "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart tomcat-autodiscovery@${device.tomcat.instance}.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --mark name --hostname name "$@"

fi

