#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --polar disabled --text-minimum 8 --text-maximum 1024 --required --url-path-abempty path --relation-base /etc/device/services/db/postgresql/database --relation-name name --relation-suffix .txt --relation database --relation-base /etc/device/services/www/virtualhost --relation-name name --relation-suffix .txt --relation virtualhost --relation-base /etc/device/services/www/auth --relation-name name --relation-suffix .txt --relation auth"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart tomcat-autodiscovery@${device.tomcat.instance}.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

